# Generated by Django 5.0 on 2023-12-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_artist_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='cover',
            field=models.ImageField(default='', upload_to='artist/covers/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(upload_to='artist/images/'),
        ),
    ]
