# Generated by Django 5.0 on 2023-12-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_artist_cover_alter_artist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='artist/covers/'),
        ),
    ]
