# Generated by Django 4.2.7 on 2023-12-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_customer_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='followed_artist',
        ),
        migrations.AddField(
            model_name='customer',
            name='followed_artists',
            field=models.ManyToManyField(blank=True, null=True, related_name='followed_artists', to='user.artist'),
        ),
    ]
