# Generated by Django 4.2.7 on 2023-12-20 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_customer_gender'),
        ('song', '0003_alter_song_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='user.customer'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(related_name='songs', to='user.artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='genres',
            field=models.ManyToManyField(related_name='songs', to='song.genre'),
        ),
        migrations.AlterField(
            model_name='song',
            name='playlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='songs', to='song.playlist'),
        ),
    ]
